### ISSUE TITLE
symlink(): Cannot create symlink, error code(1314)

### ISSUE THREAD

**Issue by MKyalo** [DezMonT765/yii2-advanced-template-rbac#1]
Hi.I installed evertything successfully via composer.However when i try to register a user on the frontend i get (symlink(): Cannot create symlink, error code(1314)) error
I tried disabling link to assetManager by adding

 'assetManager' => [
            'linkAssets' => true
        ],

![symlink_error](https://cloud.githubusercontent.com/assets/11440280/9849062/dc1ead9e-5aef-11e5-9beb-194e8767896e.png)

**Comment by DezMonT765** [comment]
Hi, i've made new release 0.0.6 with small fix, that could solve your problem. Please check it

**Comment by MKyalo** [comment]
Hi Dez.Thanks for that. It has solved the problem. However I dont know whether its something i am not doin well but after i signup it gives me an invalid parameter error view file \common/mail\email-verification.php does not exist. How do i solve this?
![error](https://cloud.githubusercontent.com/assets/11440280/9849826/25956ed4-5af7-11e5-8554-910b07e515ef.png)

**Comment by DezMonT765** [comment]
This is beacause you need an email template file "common/mail/email-verification.php". Sorry for this issue. In next releases, i want to implement a db-related mail-template system, so templates will be stored in db, not in files.

**Comment by MKyalo** [comment]
Okay Dez. Thanks for your help. I will try and work on it.
