### ISSUE TITLE
user without email confirmation login

### ISSUE THREAD

**Issue by Umarali33** [DezMonT765/yii2-advanced-template-rbac#6]
when user sign up, system send a confirmation email to user it work good but without any email confirmation system automatic login or user can login. How can i solve this that user should confirm email before login and if user not confirmed an email user can't be login?

**Comment by DezMonT765** [comment]
You should create user with status INACTIVE(0 in db) by default, and then, when he confirms his email, you should change this status to ACTIVE(1 in db). Please look to the common\models\User, and find  there STATUS_INACTIVE, and STATUS_ACTIVE constants.

**Comment by Umarali33** [comment]
yes it works properly when user sign up status is 0 in db when user confirm its status is 1, but when user status is 0 or user not confirm email verification, user can login to system without confirm an email why?
